import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsRecommendations: SidebarsConfig = {
  recommendationsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsRecommendations;
